# Generated by Django 3.2.20 on 2023-10-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0010_creatureset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatureset',
            name='type',
            field=models.TextField(choices=[('MONSTER_TYPE', 'Monster Type'), ('TAG', 'Tag')]),
        ),
    ]
