# Generated by Django 3.2.20 on 2023-10-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0011_alter_creatureset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatureset',
            name='type',
            field=models.TextField(choices=[('TYPE', 'Type'), ('TAG', 'Tag')]),
        ),
    ]
