# Generated by Django 3.2.20 on 2023-10-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0012_alter_creatureset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='creature',
            name='subtype',
        ),
        migrations.RemoveField(
            model_name='creatureset',
            name='type',
        ),
        migrations.AddField(
            model_name='creatureset',
            name='set_type',
            field=models.TextField(choices=[('TAG', 'Tag')], default='TAG'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creature',
            name='type',
            field=models.ForeignKey(help_text='Type of creature.', on_delete=django.db.models.deletion.CASCADE, to='api_v2.creaturetype'),
        ),
    ]
