# Generated by Django 3.2.20 on 2023-11-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0029_auto_20231105_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatureset',
            name='type',
            field=models.CharField(blank=True, choices=[('environment', 'Environment'), ('tag', 'Tag')], help_text='CreatureSet type.', max_length=200, null=True),
        ),
    ]
